name: mobile_assignment
description: "Used for Mobile Application assignment"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  image: ^4.5.4
  firebase_storage: ^13.0.1
  http: ^1.5.0
  firebase_storage_web: ^3.6.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
