// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuVcQvre0qUz-Pdn6mtu-fFlFbDSED_4g',
    appId: '1:545680934793:web:6859d65986c60827bb4358',
    messagingSenderId: '545680934793',
    projectId: 'mobile-assignment-81ceb',
    authDomain: 'mobile-assignment-81ceb.firebaseapp.com',
    storageBucket: 'mobile-assignment-81ceb.firebasestorage.app',
    measurementId: 'G-STR49XWG35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuntfvwTkxWpknXE3PJXDs4mLfH8icyOc',
    appId: '1:545680934793:android:358fc54ef953a42dbb4358',
    messagingSenderId: '545680934793',
    projectId: 'mobile-assignment-81ceb',
    storageBucket: 'mobile-assignment-81ceb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCsC3lFwaZS2xA1i-Zq3CCoYucdi59abM',
    appId: '1:545680934793:ios:4269c94285cbcc95bb4358',
    messagingSenderId: '545680934793',
    projectId: 'mobile-assignment-81ceb',
    storageBucket: 'mobile-assignment-81ceb.firebasestorage.app',
    iosBundleId: 'tarumt.edu.mobileAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCsC3lFwaZS2xA1i-Zq3CCoYucdi59abM',
    appId: '1:545680934793:ios:4269c94285cbcc95bb4358',
    messagingSenderId: '545680934793',
    projectId: 'mobile-assignment-81ceb',
    storageBucket: 'mobile-assignment-81ceb.firebasestorage.app',
    iosBundleId: 'tarumt.edu.mobileAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuVcQvre0qUz-Pdn6mtu-fFlFbDSED_4g',
    appId: '1:545680934793:web:dabaffb9b4d1b6cabb4358',
    messagingSenderId: '545680934793',
    projectId: 'mobile-assignment-81ceb',
    authDomain: 'mobile-assignment-81ceb.firebaseapp.com',
    storageBucket: 'mobile-assignment-81ceb.firebasestorage.app',
    measurementId: 'G-T7Q5FR3DVF',
  );

}